name: MinecraftAnimationTool
version: '1.2'
main: fr.bloup.minecraftAnimationTool.MinecraftAnimationTool
api-version: '1.20'
authors: [ bloup ]
softdepend: [ PlaceholderAPI, MythicMobs ]
commands:
  minecraftanimationtool:
    description: "Main command"
  mat:
    description: "Shortcut for main command"
permissions:
  mat.command:
    default: op